language: node_js
node_js:
- '6'
- node
env:
  - CXX=g++-4.8 PATH=$PATH:${HOME}/google-cloud-sdk/bin
services:
  - docker
before_install:
  - docker version
  - openssl aes-256-cbc -K $encrypted_80a6818a5b93_key -iv $encrypted_80a6818a5b93_iv -in client-secret.json.enc -out client-secret.json -d
  - curl -s 'https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-168.0.0-linux-x86_64.tar.gz' > ${HOME}/google-cloud-sdk.tar.gz
  - tar -xzf $HOME/google-cloud-sdk.tar.gz -C $HOME
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 $HOME/google-cloud-sdk/install.sh
  - source $HOME/google-cloud-sdk/path.bash.inc
  - source $HOME/google-cloud-sdk/completion.bash.inc
  - gcloud auth activate-service-account --key-file client-secret.json
before_script:
- npm install
script:
- "./travis-build.sh"
after_success:
  - ./push_image.sh
